pipeline:
  name: Build Deploy-Netflix-Clone-on-Kubernetes
  identifier: Build_VishalTx_Deploy_Netflix_Clone_on_Kubernetes_1758196580502
  projectIdentifier: ApplicationsKubernetes
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1711001392468
        repoName: VishalTx/Deploy-Netflix-Clone-on-Kubernetes
        build: <+input>
