name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vishal7500/netflix_clone:latest
    - name: Docker Login
      run: docker login -u vishal7500 -p 
    - name: Push the Docker image
      run: docker push vishal7500/netflix_clone:latest





